// @generated by `pnpm fate generate`
import type { AppRouter, Comment, Post, User } from '@app/server/src/router.ts';
import { createTRPCProxyClient } from '@trpc/client';
import { inferRouterInputs, inferRouterOutputs } from '@trpc/server';
import { clientRoot, createClient, createTRPCTransport, mutation } from 'react-fate';

type TRPCClientType = ReturnType<typeof createTRPCProxyClient<AppRouter>>;
type RouterInputs = inferRouterInputs<AppRouter>;
type RouterOutputs = inferRouterOutputs<AppRouter>;

const mutations = {
  'comment.add': mutation<Comment, RouterInputs['comment']['add'], RouterOutputs['comment']['add']>(
    'Comment',
  ),
  'comment.delete': mutation<
    Comment,
    RouterInputs['comment']['delete'],
    RouterOutputs['comment']['delete']
  >('Comment'),
  'post.like': mutation<Post, RouterInputs['post']['like'], RouterOutputs['post']['like']>('Post'),
  'post.unlike': mutation<Post, RouterInputs['post']['unlike'], RouterOutputs['post']['unlike']>(
    'Post',
  ),
  'user.update': mutation<User, RouterInputs['user']['update'], RouterOutputs['user']['update']>(
    'User',
  ),
} as const;

const roots = {
  comment: clientRoot<RouterOutputs['comment']['byId'], 'Comment'>('Comment'),
  commentSearch: clientRoot<RouterOutputs['comment']['search'], 'Comment'>('Comment'),
  post: clientRoot<RouterOutputs['post']['byId'], 'Post'>('Post'),
  posts: clientRoot<RouterOutputs['post']['list'], 'Post'>('Post'),
  viewer: clientRoot<RouterOutputs['user']['viewer'], 'User'>('User'),
} as const;

type GeneratedClientMutations = typeof mutations;
type GeneratedClientRoots = typeof roots;

declare module 'react-fate' {
  interface ClientMutations extends GeneratedClientMutations {}
  interface ClientRoots extends GeneratedClientRoots {}
}

export const createFateClient = (options: {
  links: Parameters<typeof createTRPCProxyClient>[0]['links'];
}) => {
  const trpcClient = createTRPCProxyClient<AppRouter>(options);

  const trpcMutations = {
    'comment.add': (client: TRPCClientType) => client.comment.add.mutate,
    'comment.delete': (client: TRPCClientType) => client.comment.delete.mutate,
    'post.like': (client: TRPCClientType) => client.post.like.mutate,
    'post.unlike': (client: TRPCClientType) => client.post.unlike.mutate,
    'user.update': (client: TRPCClientType) => client.user.update.mutate,
  } as const;

  return createClient<[GeneratedClientRoots, GeneratedClientMutations]>({
    mutations,
    roots,
    transport: createTRPCTransport<AppRouter, typeof trpcMutations>({
      byId: {
        Comment:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.comment.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        Post:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.post.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
      },
      client: trpcClient,
      queries: {
        viewer: (client: TRPCClientType) => client.user.viewer.query,
      },
      lists: {
        commentSearch: (client: TRPCClientType) => client.comment.search.query,
        posts: (client: TRPCClientType) => client.post.list.query,
      },
      mutations: trpcMutations,
    }),
    types: [
      {
        type: 'User',
      },
      {
        fields: {
          author: { type: 'User' },
          comments: { listOf: 'Comment' },
        },
        type: 'Post',
      },
      {
        fields: {
          author: { type: 'User' },
          post: { type: 'Post' },
        },
        type: 'Comment',
      },
    ],
  });
};
