packages:
  - client
  - server

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.18
  vite-plus: ^0.1.18
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.18

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - prisma
  - unrs-resolver

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
